sonar.projectKey=AbhishaBhat_BloodBank
sonar.organization=abhishabhat
sonar.host.url=https://sonarcloud.io
sonar.sources=.

# Memory fix
sonar.javascript.node.maxspace=512

# Exclude heavy files that cause memory issues
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/*.test.js,**/dependency-check-report.xml

# Exclude test files from coverage
sonar.coverage.exclusions=**/node_modules/**,**/build/**